const LIST_WALLETS = 'WALLETS@LIST';
const CREATE_WALLET = 'WALLETS@CREATE';
const SOFT_DELETE_WALLET = 'WALLETS@SOFT_DELETE';

module.exports = {
  LIST_WALLETS,
  CREATE_WALLET,
  SOFT_DELETE_WALLET,
};
