const LIST_WHISTORY = 'WHISTORY@LIST';
const ADD_WHISTORY = 'WHISTORY@ADD';
const SOFT_DELETE_WHISTORY = 'WHISTORY@SOFT_DELETE';
const HARD_DELETE_WHISTORY = 'WHISTORY@HARD_DELETE';
const RESTORE_WHISTORY = 'WHISTORY@RESTORE';

module.exports = {
  LIST_WHISTORY,
  ADD_WHISTORY,
  SOFT_DELETE_WHISTORY,
  HARD_DELETE_WHISTORY,
  RESTORE_WHISTORY,
};
