const LIST_WHISTORY = 'WHISTORY@LIST';
const ADD_WHISTORY = 'WHISTORY@ADD';
const SOFT_DELETE_WHISTORY = 'WHISTORY@SOFT_DELETE_WHISTORY';

module.exports = {
  LIST_WHISTORY,
  ADD_WHISTORY,
  SOFT_DELETE_WHISTORY,
};
