const LIST_CURRENCIES = 'CURRENCIES@LIST';
const CREATE_CURRENCY = 'CURRENCIES@CREATE';
const SOFT_DELETE_CURRENCY = 'CURRENCIES@SOFT_DELETE';
const RESTORE_CURRENCY = 'CURRENCIES@RESTORE';
const HARD_DELETE_CURRENCY = 'CURRENCIES@HARD_DELETE';

module.exports = {
  LIST_CURRENCIES,
  CREATE_CURRENCY,
  SOFT_DELETE_CURRENCY,
  RESTORE_CURRENCY,
  HARD_DELETE_CURRENCY,
};
