const LIST_CURRENCIES = 'CURRENCIES@LIST';
const CREATE_CURRENCY = 'CURRENCIES@CREATE';
const SOFT_DELETE_CURRENCY = 'CURRENCIES@SOFT_DELETE';

module.exports = {
  LIST_CURRENCIES,
  CREATE_CURRENCY,
  SOFT_DELETE_CURRENCY,
};
